main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),
]

urls.py
from django.urls import path

from . import views


app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("register/", views.register, name="register"),
    path("login/", views.login, name='login'),
    path("logout", views.logout, name='logout')
]

models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Question(models.Model):
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")


class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

class PollUser(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    country = models.CharField(max_length=50)

views.py
#
import json

#
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as _login, logout as _logout


#
from .models import Choice, Question, PollUser

def index(request):
    if request.user.is_authenticated:
        latest_question_list = Question.objects.order_by("-pub_date")[:5]
        context = {
            "latest_question_list": latest_question_list,
            "user": request.user
        }
        return render(request, "polls/index.html", context)
    else:
        return HttpResponseRedirect('/polls/login')

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    print("POST DATA", request.POST)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
    

def register(request):
    if request.method == "GET":
        return render(request, "polls/register.html", {})
    else:
        try:
            first_name = request.POST["firstname"]
            last_name = request.POST["lastname"]
            email = request.POST["email"]
            country = request.POST["country"]
            password = request.POST["password"]
            repeat_password = request.POST["repeat_password"]
        except:
            return render(request, "polls/register.html", {"error_message": "Missed Field"})        

        if password != repeat_password:
            return render(request, "polls/register.html", {"error_message": "Password not match."})        

    user = User.objects.create_user(username=email, email=email, password=password)
    user.first_name=first_name
    user.last_name = last_name
    user.save()
    
    poll_user = PollUser(user=user, country=country)
    poll_user.save()

    return  HttpResponseRedirect('/polls/login/')

def login(request):
    if request.method == "GET":
        return render(request, 'polls/login.html', {})
    else:
        try:
            email = request.POST["email"]
            password = request.POST["password"]
        except:
            return render(request, "polls/login.html", {"error_message": "Missed Field"}) 
        
    user = authenticate(username=email, password=password)
    print("USER", email, password)
    if user:
        _login(request, user)
        return HttpResponseRedirect('/polls/')

    else:
        return render(request, "polls/login.html", {"error_message": "Email or password is incorrect."}) 


def logout(request):
    _logout(request)
    return HttpResponseRedirect("/polls/login")

templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

templates/polls/index.html
<h1>Welcome {{user.first_name}} {{ user.last_name}}</h1>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<br>
<br>
<br>
<a href="{% url 'polls:logout' %}">logout</a>

templates/polls/login.html
<form action="{% url 'polls:login' %}" method="post">
    {% csrf_token %}
    <legend><h1>login</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}    
  
    
    <input type="text" name="email" id="email" value="" placeholder="Email">
    <br>
    <input type="password" name="password" id="password" value="" placeholder="Password">
    <br>
    <input type="submit" value="login">
</form>

templates/polls/register.html
<form action="{% url 'polls:register' %}" method="post">
    {% csrf_token %}
    <legend><h1>Register</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}    
  
    <input type="text" name="firstname" id="firstname" value="" placeholder="Firstname">
    <br>
    <input type="text" name="lastname" id="lastname" value="" placeholder="Last Name">
    <br>
    <input type="text" name="email" id="email" value="" placeholder="Email">
    <br>
    <input type="text" name="country" id="country" value="" placeholder="Country">
    <br>
    <input type="password" name="password" id="password" value="" placeholder="Password">
    <br>
    <input type="password" name="repeat_password" id="repeat_password" value="" placeholder="Repeat Password">
    <br> 
    <input type="submit" value="Register">
</form>

templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>